CREATE DATABASE Grocery_store_management;
USE Grocery_store_management;

-- 1. Supplier Table
CREATE TABLE IF NOT EXISTS supplier (
    sup_id TINYINT PRIMARY KEY,
    sup_name VARCHAR(255),
    address TEXT
);

-- 2. Categories Table
CREATE TABLE IF NOT EXISTS categories (
    cat_id TINYINT PRIMARY KEY,
    cat_name VARCHAR(255)
);

-- 3. Employees Table
CREATE TABLE IF NOT EXISTS employees (
    emp_id TINYINT PRIMARY KEY,
    emp_name VARCHAR(255),
    hire_date VARCHAR(255)
);

-- 4. Customers Table
CREATE TABLE IF NOT EXISTS customers (
    cust_id SMALLINT PRIMARY KEY,
    cust_name VARCHAR(255),
    address TEXT
);

-- 5. Products Table
CREATE TABLE IF NOT EXISTS products (
    prod_id TINYINT PRIMARY KEY,
    prod_name VARCHAR(255),
    sup_id TINYINT,
    cat_id TINYINT,
    price DECIMAL(10,2),
    FOREIGN KEY (sup_id) REFERENCES supplier(sup_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (cat_id) REFERENCES categories(cat_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

-- 6. Orders Table
CREATE TABLE IF NOT EXISTS orders (
    ord_id SMALLINT PRIMARY KEY,
    cust_id SMALLINT,
    emp_id TINYINT,
    order_date VARCHAR(255),
    FOREIGN KEY (cust_id) REFERENCES customers(cust_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (emp_id) REFERENCES employees(emp_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

-- 7. Order_Details Table
CREATE TABLE IF NOT EXISTS order_details (
    ord_detID SMALLINT AUTO_INCREMENT PRIMARY KEY,
    ord_id SMALLINT,
    prod_id TINYINT,
    quantity TINYINT,
    each_price DECIMAL(10,2),
    total_price DECIMAL(10,2),
    FOREIGN KEY (ord_id) REFERENCES orders(ord_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (prod_id) REFERENCES products(prod_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);



#All tables
select*from supplier;
select*from categories;
select*from employees;
select*from customers;
select*from products;
select*from orders;
select*from order_details;


#Analysis Questions
-- 1️. Customer Insights
-- How many unique customers have placed orders?
select count(distinct(cust_id)) as number_of_customers from orders;

-- Which customers have placed the highest number of orders?
select t.cust_name , t.number_of_orders
from(select c.cust_id,c.cust_name,count(o.ord_id) as number_of_orders from customers c
		join orders o
			on c.cust_id=o.cust_id
				group by c.cust_id,c.cust_name ) as t
order by t.number_of_orders desc
limit 5;

-- What is the total and average purchase value per customer?
select c.cust_id,c.cust_name,avg(od.total_price) as avg_price ,sum(total_price) as total_price
from order_details od
join orders o on od.ord_id=o.ord_id
join customers c on c.cust_id=o.cust_id
group by c.cust_id,c.cust_name
order by cust_id;

-- Who are the top 5 customers by total purchase amount?
select c.cust_id,c.cust_name,sum(total_price) as total_price
from order_details od
join orders o on od.ord_id=o.ord_id
join customers c on c.cust_id=o.cust_id
group by c.cust_id,c.cust_name
order by total_price desc
limit 5;

#2. Product Performance
-- How many products exist in each category?
select c.cat_name,count(p.prod_name) as total_products
from products p
join categories c 
on p.cat_id=c.cat_id
group by c.cat_name
order by total_products desc;

-- What is the average price of products by category?
select c.cat_name,avg(p.price) as avg_price
from products p
join categories c 
on p.cat_id=c.cat_id
group by c.cat_name;

-- Which products have the highest total sales volume (by quantity)?
select p.prod_name,sum(od.quantity) as total_volume
from order_details od
join products p on od.prod_id=p.prod_id
group by  p.prod_name
order by total_volume desc;

-- What is the total revenue generated by each product?
select p.prod_name,sum(od.total_price) as total_revenue
from products p 
join order_details od
on p.prod_id=od.prod_id
group by p.prod_name;

-- How do product sales vary by category and supplier?
SELECT 
    t.cat_name,
    t.sup_name,
    SUM(t.total_sales) AS sales_amount
FROM (
    SELECT 
        c.cat_name,
        s.sup_name,
        p.prod_name,
        SUM(od.quantity * od.each_price) AS total_sales
    FROM products p
    JOIN categories c 
        ON p.cat_id = c.cat_id
    JOIN supplier s 
        ON p.sup_id = s.sup_id
    JOIN order_details od 
        ON p.prod_id = od.prod_id
    GROUP BY c.cat_name, s.sup_name, p.prod_name
) AS t
GROUP BY t.cat_name, t.sup_name
ORDER BY sales_amount DESC;

#3. Sales and Order Trends
-- How many orders have been placed in total?
select count(*)as total_orders from orders;

-- What is the average value per order?
select ord_id,sum(total_price) from order_details group by ord_id;

-- On which dates were the most orders placed?
select order_date ,count(*) as count_ from orders
group by order_date
order by count_ desc;

-- What are the monthly trends in order volume and revenue?
select  order_date,sum(od.quantity) as total_volume,sum(od.total_price) as total_revenue
from orders o
left join order_details od on o.ord_id=od.ord_id
group by  o.order_date
order by order_date  ;

-- How do order patterns vary across weekdays and weekends?
SELECT 
    CASE 
        WHEN DAYOFWEEK(o.order_date) IN (1,7) THEN 'Weekend'  -- 1=Sunday, 7=Saturday
        ELSE 'Weekday'
    END AS day_type,
    COUNT(DISTINCT o.ord_id) AS order_count,
    SUM(od.total_price) As toal_revenue
FROM orders o
JOIN order_details od ON od.ord_id = o.ord_id
GROUP BY day_type;

#4️. Supplier Contribution
-- How many suppliers are there in the database?
select count(distinct(sup_name)) as count from supplier;

-- Which supplier provides the most products?
SELECT s.sup_id, s.sup_name, t.count_
FROM supplier s
JOIN (
    SELECT sup_id, COUNT(prod_id) AS count_
    FROM products
    GROUP BY sup_id
) AS t ON t.sup_id = s.sup_id
ORDER BY s.sup_id ;


-- What is the average price of products from each supplier?
select s.sup_name,prod_name ,avg(p.price) as avg_price
from products p
join supplier s on p.sup_id=s.sup_id
group by s.sup_name, p.prod_name;

-- Which suppliers contribute the most to total product sales (by revenue)?
select  s.sup_id,s.sup_name, sum(od.total_price) as total_revenue
from supplier s 
join products p on s.sup_id=p.sup_id
join order_details od on p.prod_id=od.prod_id
group by s.sup_id;


#Employee Performance
-- How many employees have processed orders?
select count(distinct(emp_id)) as total_employees from orders;

-- Which employees have handled the most orders?
select emp_id,count(*)as count_of_orders from orders
group by emp_id;

-- What is the total sales value processed by each employee?
select e.emp_name,sum(total_price) as total_sales
from employees e
join orders o on e.emp_id=o.emp_id
join order_details od on od.ord_id=o.ord_id
group by e.emp_name;

-- What is the average order value handled per employee?
select 	e.emp_name, avg(total_revenue) as avg_handle
from(
    select o.emp_id,o.ord_id , sum(od.total_price) as total_revenue
	from order_details od
	join orders o on  od.ord_id=o.ord_id
	group by o.emp_id,o.ord_id
    order by o.emp_id,o.ord_id
) as t
join employees e on t.emp_id=e.emp_id
group by e.emp_name
order by avg_handle;

SELECT e.emp_name, AVG(t.order_value) AS avg_order_value
FROM (
  SELECT ord_id, SUM(total_price) AS order_value
  FROM order_details
  GROUP BY ord_id
) t
JOIN orders o ON o.ord_id = t.ord_id
JOIN employees e ON e.emp_id = o.emp_id
GROUP BY e.emp_name;

select*from supplier;
select*from categories;
select*from employees;
select*from customers;
select*from products;
select*from orders;
select*from order_details;

#Order Details Deep Dive
-- What is the relationship between quantity ordered and total price?
SELECT quantity, sum(total_price) AS avg_total
FROM order_details
GROUP BY quantity
ORDER BY quantity;

-- What is the average quantity ordered per product?
select p.prod_name,avg(od.quantity) as avg_quantity
from order_details od
join products p on p.prod_id=od.prod_id
group by p.prod_name;

-- How does the unit price vary across products and orders?
select ord_id, prod_id,avg(each_price) as avg_price_unit
from order_details
group by ord_id,prod_id
order by ord_id,prod_id;





